import {ChangeDetectionStrategy, Component, booleanAttribute, computed, forwardRef, input} from '@angular/core';
import {NG_VALUE_ACCESSOR} from '@angular/forms';
import {HgControlValueAccessor} from './control-value-accessor';
export type HgInputType='text'|'email'|'password'|'search'|'number'; export type HgInputValue=string|number|null; let nextInputId=0;
@Component({selector:'hg-input',providers:[{provide:NG_VALUE_ACCESSOR,useExisting:forwardRef(()=>HgInputComponent),multi:true}],template:`<div class="field">@if(label()){<label [for]="controlId()">{{label()}}</label>}<input [id]="controlId()" [attr.name]="name()||null" [type]="type()" [value]="value()??''" [placeholder]="placeholder()" [attr.autocomplete]="autocomplete()||null" [attr.lang]="lang()||null" [attr.autocapitalize]="autocapitalize()||null" [attr.spellcheck]="spellcheck()" [readOnly]="readonly()" [attr.inputmode]="inputmode()||null" [attr.min]="min()" [attr.max]="max()" [attr.step]="step()" [disabled]="disabled()||formDisabled()" [required]="required()" [attr.aria-label]="label()?null:ariaLabel()" [attr.aria-describedby]="describedBy()" [attr.aria-invalid]="error()?true:null" (input)="onInput($event)" (blur)="markTouched()"/>@if(error()){<small class="error" [id]="errorId()">{{error()}}</small>}@else if(hint()){<small class="hint" [id]="hintId()">{{hint()}}</small>}</div>`,styleUrl:'./hg-field.scss',changeDetection:ChangeDetectionStrategy.OnPush})
export class HgInputComponent extends HgControlValueAccessor<HgInputValue>{
  readonly id=input(`hg-input-${++nextInputId}`); readonly name=input(''); readonly type=input<HgInputType>('text'); readonly label=input(''); readonly ariaLabel=input<string|null>(null); readonly autocomplete=input(''); readonly lang=input(''); readonly autocapitalize=input(''); readonly spellcheck=input(true,{transform:booleanAttribute}); readonly readonly=input(false,{transform:booleanAttribute}); readonly inputmode=input(''); readonly placeholder=input(''); readonly hint=input(''); readonly error=input(''); readonly min=input<number|null>(null); readonly max=input<number|null>(null); readonly step=input<number|string|null>(null); readonly disabled=input(false,{transform:booleanAttribute}); readonly required=input(false,{transform:booleanAttribute});
  readonly controlId=computed(()=>this.id()); readonly hintId=computed(()=>`${this.controlId()}-hint`); readonly errorId=computed(()=>`${this.controlId()}-error`); readonly describedBy=computed(()=>this.error()?this.errorId():this.hint()?this.hintId():null);
  constructor(){super('');} onInput(event:Event):void{const el=event.target as HTMLInputElement;this.updateValue(this.type()==='number'?(el.value===''?null:el.valueAsNumber):el.value);}
}
